export enum Role {
  VIEWER = 'VIEWER',
  EDITOR = 'EDITOR',
  ADMIN = 'ADMIN'
}

export enum ProcessingStatus {
  PENDING = 'PENDING',
  UPLOADING = 'UPLOADING',
  PROCESSING = 'PROCESSING',
  ANALYZING = 'ANALYZING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}

export enum SafetyStatus {
  UNKNOWN = 'UNKNOWN',
  SAFE = 'SAFE',
  FLAGGED = 'FLAGGED',
  MANUAL_REVIEW = 'MANUAL_REVIEW'
}

export interface User {
  id: string;
  name: string;
  email: string;
  role: Role;
  organizationId: string;
}

export interface Video {
  id: string;
  title: string;
  description: string;
  uploadDate: string;
  duration: string; // Display string like "10:24"
  size: string;
  uploaderId: string;
  organizationId: string;
  status: ProcessingStatus;
  safetyStatus: SafetyStatus;
  thumbnailUrl: string;
  videoUrl?: string; // URL to the actual video file
  progress: number; // 0-100
  flagReason?: string;
  aiAnalysis?: string; // Generated by Gemini
}

export interface Notification {
  id: string;
  message: string;
  type: 'info' | 'success' | 'warning' | 'error';
  timestamp: Date;
}